In [11]:
import pandas as pd
import mode_notebook_assets.practical_dashboard_displays as dis

In [19]:
# read test series
_ts = pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/shampoo.csv').set_index('Month')['Sales']

In [21]:
dis.outside_of_normal_range(_ts)

,Sales,period_value,normal_range_actionability_score,low_l2_threshold_value,low_l1_threshold_value,high_l1_threshold_value,high_l2_threshold_value
Month,,,,,,,
1-01,266.0,266.0,NaN,NaN,NaN,NaN,NaN
1-02,145.9,145.9,NaN,NaN,NaN,NaN,NaN
1-03,183.1,183.1,NaN,NaN,NaN,NaN,NaN
1-04,119.3,119.3,NaN,NaN,NaN,NaN,NaN
1-05,180.3,180.3,NaN,NaN,NaN,NaN,NaN
1-06,168.5,168.5,NaN,NaN,NaN,NaN,NaN
1-07,231.8,231.8,NaN,NaN,NaN,NaN,NaN
1-08,224.5,224.5,0.000000,-17.840000,51.415000,328.435000,397.690000
1-09,192.8,192.8,0.000000,-7.360306,58.507944,321.980944,387.849194
1-10,122.9,122.9,0.000000,-23.127667,45.751556,321.268444,390.147667
1-11,336.5,336.5,0.000000,-73.782118,16.617982,378.218382,468.618482
1-12,185.9,185.9,0.000000,-104.714121,-4.323303,397.239970,497.630788
2-01,194.3,194.3,0.000000,-82.575442,10.380474,382.204141,475.160058
2-02,149.5,149.5,0.000000,-78.216538,12.172308,373.727692,464.116538
2-03,210.1,210.1,0.000000,-74.975167,14.714333,373.472333,463.161833
2-04,273.3,273.3,0.000000,-68.898050,20.415883,377.671617,466.985550
2-05,191.4,191.4,0.000000,-73.025132,17.514618,379.673618,470.213368
2-06,287.0,287.0,0.000000,-74.573974,18.119203,388.891908,481.585085
2-07,226.0,226.0,0.000000,-71.462860,20.587918,388.791029,480.841807
2-08,303.6,303.6,0.000000,-68.279000,24.359000,394.911000,487.549000
2-09,289.9,289.9,0.000000,-53.294307,35.622843,391.291443,480.208593
2-10,421.6,421.6,0.135812,-56.153818,36.870182,408.966182,501.990182
2-11,264.5,264.5,0.000000,-70.153049,28.139996,421.312178,519.605223
2-12,342.3,342.3,0.000000,-65.929913,32.588391,426.661609,525.179913
3-01,339.7,339.7,0.000000,-49.644375,44.913083,423.142917,517.700375
3-02,440.4,440.4,0.064180,-46.431815,49.700585,434.230185,530.362585
3-03,315.9,315.9,0.000000,-51.707258,47.096396,442.311011,541.114665
3-04,439.3,439.3,0.000000,-52.014984,49.207868,454.099275,555.322127
3-05,401.3,401.3,0.000000,-41.424457,57.988293,455.639293,555.052043
3-06,437.4,437.4,0.000000,-30.087701,67.552644,458.114023,555.754368
3-07,575.5,575.5,1.010510,-28.604945,71.903155,473.935555,574.443655
3-08,407.6,407.6,0.000000,-36.279940,68.189415,486.066835,590.536190
3-09,682.0,682.0,1.486413,-48.431343,64.178095,514.615845,627.225282
3-10,475.3,475.3,0.000000,-57.718294,59.809373,529.920039,647.447706
3-11,581.3,581.3,0.353726,-51.603752,66.613689,539.483454,657.700895
3-12,646.9,646.9,0.849166,-39.397800,77.934800,547.265200,664.597800

In [22]:
dis.change_in_steady_state_long(_ts)

,Sales,period_value,change_in_steady_state_long_actionability_score,mean_of_historical_training_values,current_long_run
Month,,,,,
1-01,266.0,266.0,NaN,NaN,NaN
1-02,145.9,145.9,NaN,NaN,NaN
1-03,183.1,183.1,NaN,NaN,NaN
1-04,119.3,119.3,NaN,NaN,NaN
1-05,180.3,180.3,NaN,NaN,NaN
1-06,168.5,168.5,NaN,NaN,NaN
1-07,231.8,231.8,NaN,NaN,NaN
1-08,224.5,224.5,NaN,NaN,NaN
1-09,192.8,192.8,NaN,NaN,NaN
1-10,122.9,122.9,NaN,NaN,NaN
1-11,336.5,336.5,NaN,NaN,NaN
1-12,185.9,185.9,NaN,NaN,NaN
2-01,194.3,194.3,NaN,NaN,NaN
2-02,149.5,149.5,0.00,184.985714,0.0
2-03,210.1,210.1,0.00,184.985714,0.0
2-04,273.3,273.3,0.00,189.925000,1.0
2-05,191.4,191.4,0.00,189.925000,2.0
2-06,287.0,287.0,0.00,190.244444,3.0
2-07,226.0,226.0,0.00,190.244444,4.0
2-08,303.6,303.6,0.00,183.510000,5.0
2-09,289.9,289.9,0.00,183.510000,6.0
2-10,421.6,421.6,0.00,197.418182,4.0
2-11,264.5,264.5,0.00,197.418182,5.0
2-12,342.3,342.3,0.00,196.458333,6.0
3-01,339.7,339.7,0.01,196.458333,7.0
3-02,440.4,440.4,0.51,196.292308,8.0
3-03,315.9,315.9,1.01,196.292308,9.0
3-04,439.3,439.3,1.51,192.950000,10.0
3-05,401.3,401.3,2.01,192.950000,11.0
3-06,437.4,437.4,2.51,194.093333,12.0
3-07,575.5,575.5,3.01,194.093333,13.0
3-08,407.6,407.6,3.51,199.043750,14.0
3-09,682.0,682.0,4.01,199.043750,15.0
3-10,475.3,475.3,4.51,198.594118,16.0
3-11,581.3,581.3,5.01,198.594118,17.0
3-12,646.9,646.9,5.01,203.505556,17.0

In [23]:
dis.sudden_change(_ts)

,Sales,period_value,sudden_change_actionability_score,sudden_change_l1_threshold_value,sudden_change_l2_threshold_value,most_recent_period_change
Month,,,,,,
1-01,266.0,266.0,NaN,NaN,NaN,NaN
1-02,145.9,145.9,NaN,NaN,NaN,NaN
1-03,183.1,183.1,NaN,NaN,NaN,NaN
1-04,119.3,119.3,NaN,NaN,NaN,NaN
1-05,180.3,180.3,NaN,NaN,NaN,NaN
1-06,168.5,168.5,NaN,NaN,NaN,NaN
1-07,231.8,231.8,0.0,194.674000,292.011000,63.3
1-08,224.5,224.5,0.0,170.273571,255.410357,-7.3
1-09,192.8,192.8,0.0,161.946750,242.920125,-31.7
1-10,122.9,122.9,0.0,169.349667,254.024500,-69.9
1-11,336.5,336.5,0.0,222.261900,333.392850,213.6
1-12,185.9,185.9,0.0,246.825545,370.238318,-150.6
2-01,194.3,194.3,0.0,228.545750,342.818625,8.4
2-02,149.5,149.5,0.0,222.234231,333.351346,-44.8
2-03,210.1,210.1,0.0,220.514786,330.772179,60.6
2-04,273.3,273.3,0.0,219.591400,329.387100,63.2
2-05,191.4,191.4,0.0,222.605250,333.907875,-81.9
2-06,287.0,287.0,0.0,227.899765,341.849647,95.6
2-07,226.0,226.0,0.0,226.320333,339.480500,-61.0
2-08,303.6,303.6,0.0,227.764105,341.646158,77.6
2-09,289.9,289.9,0.0,218.615850,327.923775,-13.7
2-10,421.6,421.6,0.0,228.713143,343.069714,131.7
2-11,264.5,264.5,0.0,241.667864,362.501795,-157.1
2-12,342.3,342.3,0.0,242.221696,363.332543,77.8
3-01,339.7,339.7,0.0,232.483375,348.725063,-2.6
3-02,440.4,440.4,0.0,236.355600,354.533400,100.7
3-03,315.9,315.9,0.0,242.923269,364.384904,-124.5
3-04,439.3,439.3,0.0,248.871222,373.306833,123.4
3-05,401.3,401.3,0.0,244.420821,366.631232,-38.0
3-06,437.4,437.4,0.0,240.063103,360.094655,36.1
3-07,575.5,575.5,0.0,247.113900,370.670850,138.1
3-08,407.6,407.6,0.0,256.853226,385.279839,-167.9
3-09,682.0,682.0,0.0,276.866813,415.300219,274.4
3-10,475.3,475.3,0.0,288.959000,433.438500,-206.7
3-11,581.3,581.3,0.0,290.654912,435.982368,106.0
3-12,646.9,646.9,0.0,288.479400,432.719100,65.6